### ISSUE TITLE
問題一覧に色付け

### ISSUE THREAD

**Issue by Goryudyuma** [Goryudyuma/kstmctf#11]
問題を開いた問題についてはbg-warning、解けた問題についてはbg-successで、solved okだけでなくわかりやすく解けた問題と解いている問題とまだ開けていない問題を見やすくわける。

**Comment by ugwis** [comment]
その人が問題を開いたかどうかを問題一覧取得時のデータに追記してください

**Comment by Goryudyuma** [comment]
できました
